# Generated by Django 4.1.3 on 2022-11-05 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_alter_song_release_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='release_date',
            new_name='released_date',
        ),
    ]
