# Generated by Django 4.1.3 on 2022-11-05 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0004_rename_release_date_song_released_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='released_date',
            new_name='song_released_date',
        ),
    ]
